// modules/mock.ts
import { type Device } from "./DevicesTypes";

export const DEVICES_MOCK: Device[] = [
  {
    device_id: 1,
    name: "Универсальный адаптер BMW Step-In",
    type: "Адаптер",
    power_nominal: 10,
    resistance: 1.2,
    voltage_nominal: 12.0,
    coeff_reserve: 2.0,
    coeff_efficiency: 0.85,
    current_required: 0.83,
    description: "Вставной адаптер Snap-In предназначен для всех подходящих телефонов с разъемом Micro USB. Помимо зарядки телефона обеспечивает также улучшенный прием и надежное крепление. Благодаря разъему USB записанная на телефоне музыка может удобно воспроизводиться через динамики аудиосистемы BMW.",
    image: "1.jpg",
    in_stock: true,
    is_delete: false
  },
  {
    device_id: 2,
    name: "Адаптер BMW Step-In для мобильных телефонов Apple",
    type: "Адаптер",
    power_nominal: 15,
    resistance: 0.8,
    voltage_nominal: 12.0,
    coeff_reserve: 1.8,
    coeff_efficiency: 0.88,
    current_required: 1.25,
    description: "Специально разработан для устройств Apple. Обеспечивает быструю зарядку и стабильное соединение с медиасистемой BMW.",
    image: "2.jpg",
    in_stock: true,
    is_delete: false
  },
  {
    device_id: 3,
    name: "Автомобильный отопитель BMW",
    type: "Отопитель",
    power_nominal: 150,
    resistance: 0.096,
    voltage_nominal: 12.0,
    coeff_reserve: 1.5,
    coeff_efficiency: 0.92,
    current_required: 12.5,
    description: "Дополнительный отопитель салона с дистанционным управлением. Обеспечивает комфортную температуру в холодное время года.",
    image: "3.jpg",
    in_stock: true,
    is_delete: false
  },
  {
    device_id: 4,
    name: "Автомобильный отопитель BMW Premium",
    type: "Отопитель",
    power_nominal: 200,
    resistance: 0.072,
    voltage_nominal: 12.0,
    coeff_reserve: 1.6,
    coeff_efficiency: 0.94,
    current_required: 16.67,
    description: "Усовершенствованная модель отопителя с цифровым управлением и таймером. Поддерживает заданную температуру автоматически.",
    image: "4.jpg",
    in_stock: true,
    is_delete: false
  },
  {
    device_id: 5,
    name: "Переходник Micro USB",
    type: "Адаптер",
    power_nominal: 5,
    resistance: 2.88,
    voltage_nominal: 12.0,
    coeff_reserve: 2.5,
    coeff_efficiency: 0.82,
    current_required: 0.42,
    description: "Компактный переходник для подключения устройств с Micro USB к медиасистеме BMW. Обеспечивает зарядку и передачу данных.",
    image: "5.jpg",
    in_stock: true,
    is_delete: false
  },
  {
    device_id: 6,
    name: "Адаптер Media для Apple iPod / iPhone",
    type: "Адаптер",
    power_nominal: 12,
    resistance: 1.2,
    voltage_nominal: 12.0,
    coeff_reserve: 2.0,
    coeff_efficiency: 0.86,
    current_required: 1.0,
    description: "Адаптер для полной интеграции устройств Apple с медиасистемой BMW. Поддержка управления через iDrive.",
    image: "6.jpg",
    in_stock: true,
    is_delete: false
  },
  {
    device_id: 7,
    name: "Музыкальный/медийный адаптер BMW для Apple iPod/iPhone",
    type: "Адаптер",
    power_nominal: 18,
    resistance: 0.8,
    voltage_nominal: 12.0,
    coeff_reserve: 1.8,
    coeff_efficiency: 0.89,
    current_required: 1.5,
    description: "Премиальный адаптер с поддержкой высококачественного звука и видео. Полная интеграция с интерфейсом iDrive.",
    image: "7.jpg",
    in_stock: true,
    is_delete: false
  },
  {
    device_id: 8,
    name: "Кабель-адаптер BMW для Micro-USB",
    type: "Адаптер",
    power_nominal: 10,
    resistance: 1.44,
    voltage_nominal: 12.0,
    coeff_reserve: 2.2,
    coeff_efficiency: 0.84,
    current_required: 0.83,
    description: "Оригинальный кабель-адаптер для устройств Android. Обеспечивает быструю зарядку и стабильное соединение.",
    image: "8.jpg",
    in_stock: true,
    is_delete: false
  }
];